### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by liamxg** [toebR/30_days_map_challenge#1]
world <- ne_countries(scale = "medium", returnclass = "sf")
Error in st_as_sfc.SpatialPolygons(sp::geometry(x), ...) : 
  package rgeos required for finding out which hole belongs to which exterior ring

**Comment by toebR** [comment]
As the error states: packages rgeos is required.
To solve this issue you can run the following command: install.packages('rgeos')
Let me know if it worked.

**Comment by liamxg** [comment]
thanks for your help. i will try it.

**Comment by liamxg** [comment]
anther issue, thanks.

loadfonts(device = "win")
Error in windowsFonts() : could not find function "windowsFonts"

**Comment by toebR** [comment]
Do you use windows? This function imports the fonts registered by windows operating system. You could also just try loadfonts().

**Comment by toebR** [comment]
Closed due to no response to suggestions

**Comment by liamxg** [comment]
I use Mac.
